use std::{collections::BTreeMap, fs, path::Path};

use serde::{Deserialize, Serialize};

#[derive(Deserialize, Serialize)]
pub(super) struct Sample {
  pub(super) file: String,
  pub(super) source: String,
}

#[test]
#[ignore = "copies local mod assets and regenerates per-file test cases"]
fn extract_source_samples() {
  let base = Path::new(env!("CARGO_MANIFEST_DIR"));
  let source = base.join("asset/source");
  assert!(source.is_dir(), "missing {}", source.display());
  let mut paths = walkdir::WalkDir::new(&source)
    .follow_links(false)
    .into_iter()
    .map(|entry| entry.expect("cannot enumerate source assets"))
    .filter(|entry| entry.file_type().is_file())
    .map(|entry| entry.into_path())
    .filter(|path| {
      path.extension().and_then(|value| value.to_str()).is_some_and(|extension| {
        ["ymap", "ybn", "ymt", "ynd", "ytyp"].contains(&extension.to_ascii_lowercase().as_str())
      }) && !path
        .components()
        .any(|component| matches!(component.as_os_str().to_str(), Some("_backup" | "_omit")))
    })
    .collect::<Vec<_>>();
  paths.sort();
  assert!(!paths.is_empty(), "source corpus is empty");
  let mut samples = BTreeMap::<String, BTreeMap<String, Sample>>::new();
  for path in paths {
    let extension = path.extension().unwrap().to_str().unwrap().to_ascii_lowercase();
    let resource = path
      .ancestors()
      .skip(1)
      .take_while(|parent| *parent != source)
      .find(|parent| {
        parent.join("fxmanifest.lua").is_file() || parent.join("__resource.lua").is_file()
      })
      .unwrap_or_else(|| {
        let relative = path.strip_prefix(&source).unwrap();
        let mut components = relative.components();
        let mut root = source.join(components.next().unwrap());
        while root.file_name().unwrap().to_string_lossy().starts_with('[') {
          root.push(components.next().expect("group has no resource"));
        }
        path.ancestors().find(|parent| *parent == root).unwrap()
      });
    let mut file = format!(
      "{}___{}",
      resource.file_name().unwrap().to_str().unwrap(),
      path.file_name().unwrap().to_str().unwrap()
    );
    let relative = path.strip_prefix(base).unwrap().to_str().unwrap().replace('\\', "/");
    let group = samples.entry(extension).or_default();
    if let Some(previous) = group.get(&file) {
      if fs::read(base.join(&previous.source)).unwrap() == fs::read(&path).unwrap() {
        continue;
      }
      let variant = path
        .parent()
        .unwrap()
        .strip_prefix(resource)
        .unwrap()
        .components()
        .map(|part| part.as_os_str().to_str().unwrap())
        .collect::<Vec<_>>()
        .join("__");
      file = format!(
        "{}__{variant}___{}",
        resource.file_name().unwrap().to_str().unwrap(),
        path.file_name().unwrap().to_str().unwrap()
      );
      assert!(!group.contains_key(&file), "ambiguous fixture name: {relative}");
    }
    group.insert(
      file.clone(),
      Sample {
        file,
        source: relative,
      },
    );
  }
  for extension in ["ymap", "ybn", "ymt", "ynd", "ytyp"] {
    let group = samples.remove(extension).unwrap_or_default();
    let output = base.join("asset/sample").join(extension);
    fs::create_dir_all(&output).unwrap();
    let entries = group.into_values().collect::<Vec<_>>();
    let mut cases = String::from("// Generated by extract_source_samples; do not edit manually.\n");
    for (index, sample) in entries.iter().enumerate() {
      fs::copy(base.join(&sample.source), output.join(&sample.file)).unwrap();
      cases.push_str(&format!("sample_case!(case_{index:04}, {:?});\n", sample.file));
    }
    fs::write(output.join("manifest.json"), serde_json::to_vec_pretty(&entries).unwrap()).unwrap();
    fs::write(base.join(format!("src/core/format/gamefile/test/{extension}_cases.rs")), cases)
      .unwrap();
    eprintln!("{extension}: extracted {} fixtures to {}", entries.len(), output.display());
  }
}
