[package]
name = "mlo_merger"
version = "0.1.0"
edition = "2024"
default-run = "mlo_merger"

[features]
typescript = ["dep:specta"]

[dependencies]
bpaf = "0.9.22"
chrono = { version = "0.4.43", features = ["clock"] }
deku = "0.20.3"
flate2 = "1.1"
globset = "0.4"
indexmap = { version = "2.7.2", features = ["serde"] }
log = "0.4"
netcorehost = "0.22.0"
quick-xml = { version = "0.39.0", features = ["serialize", "overlapped-lists"] }
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
simplelog = "0.12"
specta = { version = "1.0.5", optional = true, features = ["export"] }
structdiff = { version = "0.7.3", features = ["debug_diffs", "serde"] }
toml = "0.9.11"
walkdir = "2.5.0"

[build-dependencies]
netcorehost = "0.22.0"

[[test]]
name = "gamefile_samples"
path = "src/core/format/gamefile/test/mod.rs"

[[bin]]
name = "export-types"
path = "src/bin/export_types.rs"
required-features = ["typescript"]
