tab_spaces = 2
struct_lit_single_line = false
use_small_heuristics = "Off"
single_line_if_else_max_width = 200

imports_layout = "HorizontalVertical"
fn_params_layout = "Vertical"

format_macro_bodies = false
format_macro_matchers = false
