use super::*;

pub(super) const ARRAY_INFO_HASH: u32 = 0x0000_0100;
pub(super) const STRUCTURE: u8 = 0x05;
pub(super) const STRUCTURE_POINTER: u8 = 0x07;
pub(super) const ARRAY: u8 = 0x52;

pub(super) const KNOWN_NAMES: &[&str] = &[
  "CMapTypes",
  "CMapData",
  "CEntityDef",
  "CMloInstanceDef",
  "rage__fwContainerLodDef",
  "BoxOccluder",
  "OccludeModel",
  "rage__fwInstancedMapData",
  "CTimeCycleModifier",
  "CCarGen",
  "CLODLight",
  "CDistantLODLight",
  "rage__fwPropInstanceListDef",
  "rage__fwGrassInstanceListDef",
  "rage__fwGrassInstanceListDef__InstanceData",
  "FloatXYZ",
  "x",
  "y",
  "z",
  "POINTER",
  "STRING",
  "HASH",
  "UINT",
  "USHORT",
  "BYTE",
  "FLOAT",
  "VECTOR3",
  "VECTOR4",
  "name",
  "parent",
  "flags",
  "contentFlags",
  "streamingExtentsMin",
  "streamingExtentsMax",
  "entitiesExtentsMin",
  "entitiesExtentsMax",
  "entities",
  "containerLods",
  "boxOccluders",
  "occludeModels",
  "physicsDictionaries",
  "instancedData",
  "timeCycleModifiers",
  "carGenerators",
  "LODLightsSOA",
  "LODLights",
  "DistantLODLightsSOA",
  "block",
  "archetypeName",
  "guid",
  "position",
  "Position",
  "NormalX",
  "NormalY",
  "Color",
  "Scale",
  "Ao",
  "Pad",
  "ScenarioType",
  "IgnoreMaxInRange",
  "NoSpawn",
  "StationaryReactions",
  "OnlySpawnInSameInterior",
  "SpawnedPedIsArrestable",
  "ActivateVehicleSiren",
  "AggressiveVehicleDriving",
  "LandVehicleOnArrival",
  "IgnoreThreatsIfLosNotClear",
  "EventsInRadiusTriggerDisputes",
  "AerialVehiclePoint",
  "TerritorialScenario",
  "EndScenarioIfPlayerWithinRadius",
  "EventsInRadiusTriggerThreatResponse",
  "TaxiPlaneOnGround",
  "FlyOffToOblivion",
  "InWater",
  "AllowInvestigation",
  "OpenDoor",
  "PreciseUseTime",
  "NoRespawnUntilStreamedOut",
  "NoVehicleSpawnMaxDistance",
  "ExtendedRange",
  "ShortRange",
  "HighPriority",
  "IgnoreLoitering",
  "UseSearchlight",
  "ResetNoCollisionOnCleanUp",
  "CheckCrossedArrivalPlane",
  "UseVehicleFrontForArrival",
  "IgnoreWeatherRestrictions",
  "Group",
  "ModelSet",
  "AvailabilityInMpSp",
  "Flags",
  "Radius",
  "TimeTillPedLeaves",
  "iTimeStartOverride",
  "iTimeEndOverride",
  "offsetPosition",
  "enableLimitAngle",
  "startsLocked",
  "canBreak",
  "limitAngle",
  "posn",
  "colour",
  "flashiness",
  "intensity",
  "boneTag",
  "lightType",
  "groupId",
  "timeFlags",
  "cullingPlane",
  "shadowBlur",
  "padding1",
  "padding2",
  "padding3",
  "volIntensity",
  "volSizeScale",
  "volOuterColour",
  "lightHash",
  "volOuterIntensity",
  "coronaSize",
  "volOuterExponent",
  "lightFadeDistance",
  "shadowFadeDistance",
  "specularFadeDistance",
  "volumetricFadeDistance",
  "shadowNearClip",
  "coronaZBias",
  "tangent",
  "coneInnerAngle",
  "extents",
  "projectedTextureKey",
  "doorTargetRatio",
  "audioHash",
  "instances",
  "floorId",
  "defaultEntitySets",
  "numExitPortals",
  "MLOInstflags",
  "rotation",
  "scaleXY",
  "scaleZ",
  "parentIndex",
  "lodDist",
  "childLodDist",
  "lodLevel",
  "numChildren",
  "priorityLevel",
  "extensions",
  "ambientOcclusionMultiplier",
  "artificialAmbientOcclusion",
  "tintValue",
  "iCenterX",
  "iCenterY",
  "iCenterZ",
  "iCosZ",
  "iLength",
  "iWidth",
  "iHeight",
  "iSinZ",
  "bmin",
  "bmax",
  "dataSize",
  "verts",
  "numVertsInBytes",
  "numTris",
  "minExtents",
  "maxExtents",
  "percentage",
  "range",
  "startHour",
  "endHour",
  "orientX",
  "orientY",
  "perpendicularLength",
  "carModel",
  "bodyColorRemap1",
  "bodyColorRemap2",
  "bodyColorRemap3",
  "bodyColorRemap4",
  "popGroup",
  "livery",
  "version",
  "exportedBy",
  "owner",
  "time",
  "direction",
  "falloff",
  "falloffExponent",
  "timeAndStateFlags",
  "hash",
  "coneInnerAngle",
  "coneOuterAngle",
  "coneOuterAngleOrCapExt",
  "coronaIntensity",
  "RGBI",
  "numStreetLights",
  "category",
  "ImapLink",
  "PropInstanceList",
  "GrassInstanceList",
  "BatchAABB",
  "ScaleRange",
  "LodFadeStartDist",
  "LodInstFadeRange",
  "OrientToTerrain",
  "InstanceList",
  "min",
  "max",
  "normalX",
  "normalY",
  "color",
  "scale",
  "ao",
  "pad",
  "LODTYPES_DEPTH_ORPHANHD",
  "LODTYPES_DEPTH_HD",
  "LODTYPES_DEPTH_LOD",
  "LODTYPES_DEPTH_SLOD1",
  "LODTYPES_DEPTH_SLOD2",
  "LODTYPES_DEPTH_SLOD3",
  "LODTYPES_DEPTH_SLOD4",
  "PRI_REQUIRED",
  "PRI_OPTIONAL_HIGH",
  "PRI_OPTIONAL_MEDIUM",
  "PRI_OPTIONAL_LOW",
];

/// Returns built-in field, structure, and enum names shared by META and PSO XML.
pub(crate) fn known_hash_names() -> HashMap<u32, String> {
  KNOWN_NAMES.iter().map(|name| (jenk_hash(name), (*name).to_string())).collect()
}

pub(super) fn fallback_structure(hash: u32) -> Option<MetaStructureInfo> {
  let hash_name = |name: &str| jenk_hash(name);
  let entry = |name: &str, offset, data_type, reference_key| MetaStructureEntry {
    name_hash: hash_name(name),
    data_offset: offset,
    data_type,
    unknown: 0,
    reference_type_index: 0,
    reference_key,
  };
  let array_info = |data_type, reference_key| MetaStructureEntry {
    name_hash: ARRAY_INFO_HASH,
    data_offset: 0,
    data_type,
    unknown: 0,
    reference_type_index: 0,
    reference_key,
  };
  let structure = |name: &str, size, entries| MetaStructureInfo {
    name_hash: hash_name(name),
    structure_key: 0,
    unknown_8: 0,
    unknown_12: 0,
    unknown_28: 0,
    structure_size: size,
    entries,
  };

  match hash {
    value if value == hash_name("rage__fwInstancedMapData") => Some(structure(
      "rage__fwInstancedMapData",
      48,
      vec![
        entry("ImapLink", 8, 0x4a, 0),
        array_info(STRUCTURE, hash_name("rage__fwPropInstanceListDef")),
        entry("PropInstanceList", 16, ARRAY, 0),
        array_info(STRUCTURE, hash_name("rage__fwGrassInstanceListDef")),
        entry("GrassInstanceList", 32, ARRAY, 0),
      ],
    )),
    value if value == hash_name("rage__spdAABB") => Some(structure(
      "rage__spdAABB",
      32,
      vec![entry("min", 0, 0x34, 0), entry("max", 16, 0x34, 0)],
    )),
    value if value == hash_name("rage__fwGrassInstanceListDef") => Some(structure(
      "rage__fwGrassInstanceListDef",
      96,
      vec![
        entry("BatchAABB", 0, 0x05, hash_name("rage__spdAABB")),
        entry("ScaleRange", 32, 0x33, 0),
        entry("archetypeName", 48, 0x4a, 0),
        entry("lodDist", 52, 0x15, 0),
        entry("LodFadeStartDist", 56, 0x21, 0),
        entry("LodInstFadeRange", 60, 0x21, 0),
        entry("OrientToTerrain", 64, 0x21, 0),
        array_info(STRUCTURE, hash_name("rage__fwGrassInstanceListDef__InstanceData")),
        entry("InstanceList", 72, ARRAY, 0),
      ],
    )),
    value if value == hash_name("rage__fwGrassInstanceListDef__InstanceData") => Some(structure(
      "rage__fwGrassInstanceListDef__InstanceData",
      16,
      vec![
        array_info(0x13, 0),
        entry("Position", 0, 0x50, 3),
        entry("NormalX", 6, 0x11, 0),
        entry("NormalY", 7, 0x11, 0),
        array_info(0x11, 0),
        entry("Color", 8, 0x50, 4),
        entry("Scale", 11, 0x11, 0),
        entry("Ao", 12, 0x11, 0),
        array_info(0x11, 0),
        entry("Pad", 13, 0x50, 8),
      ],
    )),
    value if value == hash_name("FloatXYZ") => Some(structure(
      "FloatXYZ",
      12,
      vec![entry("x", 0, 0x21, 0), entry("y", 4, 0x21, 0), entry("z", 8, 0x21, 0)],
    )),
    value if value == hash_name("CLODLight") => Some(structure(
      "CLODLight",
      136,
      vec![
        array_info(STRUCTURE, hash_name("FloatXYZ")),
        entry("direction", 8, ARRAY, 0),
        array_info(0x21, 0),
        entry("falloff", 24, ARRAY, 0),
        array_info(0x21, 0),
        entry("falloffExponent", 40, ARRAY, 0),
        array_info(0x15, 0),
        entry("timeAndStateFlags", 56, ARRAY, 0),
        array_info(0x15, 0),
        entry("hash", 72, ARRAY, 0),
        array_info(0x11, 0),
        entry("coneInnerAngle", 88, ARRAY, 0),
        array_info(0x11, 0),
        entry("coneOuterAngleOrCapExt", 104, ARRAY, 0),
        array_info(0x11, 0),
        entry("coronaIntensity", 120, ARRAY, 0),
      ],
    )),
    value if value == hash_name("CDistantLODLight") => Some(structure(
      "CDistantLODLight",
      48,
      vec![
        array_info(STRUCTURE, hash_name("FloatXYZ")),
        entry("position", 8, ARRAY, 0),
        array_info(0x15, 0),
        entry("RGBI", 24, ARRAY, 0),
        entry("numStreetLights", 40, 0x13, 0),
        entry("category", 42, 0x13, 0),
      ],
    )),
    value if value == hash_name("CLightAttrDef") => Some(structure(
      "CLightAttrDef",
      160,
      vec![
        array_info(0x21, 0),
        entry("posn", 8, 0x50, 3),
        array_info(0x11, 0),
        entry("colour", 20, 0x50, 3),
        entry("flashiness", 23, 0x11, 0),
        entry("intensity", 24, 0x21, 0),
        entry("flags", 28, 0x15, 0),
        entry("boneTag", 32, 0x12, 0),
        entry("lightType", 34, 0x11, 0),
        entry("groupId", 35, 0x11, 0),
        entry("timeFlags", 36, 0x15, 0),
        entry("falloff", 40, 0x21, 0),
        entry("falloffExponent", 44, 0x21, 0),
        array_info(0x21, 0),
        entry("cullingPlane", 48, 0x50, 4),
        entry("shadowBlur", 64, 0x11, 0),
        entry("padding1", 65, 0x11, 0),
        entry("padding2", 66, 0x12, 0),
        entry("padding3", 68, 0x15, 0),
        entry("volIntensity", 72, 0x21, 0),
        entry("volSizeScale", 76, 0x21, 0),
        array_info(0x11, 0),
        entry("volOuterColour", 80, 0x50, 3),
        entry("lightHash", 83, 0x11, 0),
        entry("volOuterIntensity", 84, 0x21, 0),
        entry("coronaSize", 88, 0x21, 0),
        entry("volOuterExponent", 92, 0x21, 0),
        entry("lightFadeDistance", 96, 0x11, 0),
        entry("shadowFadeDistance", 97, 0x11, 0),
        entry("specularFadeDistance", 98, 0x11, 0),
        entry("volumetricFadeDistance", 99, 0x11, 0),
        entry("shadowNearClip", 100, 0x21, 0),
        entry("coronaIntensity", 104, 0x21, 0),
        entry("coronaZBias", 108, 0x21, 0),
        array_info(0x21, 0),
        entry("direction", 112, 0x50, 3),
        array_info(0x21, 0),
        entry("tangent", 124, 0x50, 3),
        entry("coneInnerAngle", 136, 0x21, 0),
        entry("coneOuterAngle", 140, 0x21, 0),
        array_info(0x21, 0),
        entry("extents", 144, 0x50, 3),
        entry("projectedTextureKey", 156, 0x15, 0),
      ],
    )),
    _ => None,
  }
}
