# Cargo configuration and aliases

[alias]
# Run MLO batch processing with sample data
mergexml = "run -- --merge-ymap-xml --vanilla-dir asset/vanilla/ymap.xml --mod-dir asset/mlo/ymap.xml --output-dir asset/merged/ymap.xml"
parsexml = "run -- --parse-ymap-xml -i docs/sample/sample.ymap.xml"
extract = "run -- --extract-ymap --flatten -i asset/mlo/source -o asset/mlo/ymap.extracted --vanilla-dir asset/vanilla/ymap.xml"
